# Generated by Django 4.2.21 on 2025-05-12 20:26

from django.db import migrations
import miran.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", miran.users.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_testing",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
