# Generated by Django 4.2.21 on 2025-05-16 21:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="products_pr_search__98d711_gin"
            ),
        ),
    ]
