# Generated by Django 4.2.21 on 2025-05-17 00:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_products_pr_search__98d711_gin"),
    ]

    operations = [TrigramExtension()]
